### PR TITLE
[CLEANUP] Autoformat all code with PhpStorm

### PR DESCRIPTION
**Pull request by oliverklee**
This is the formatting done with PhpStorm's default PSR-2 rules.

This will make autoformat after doing code changes not affect any other
parts of the code.

### CODE REVIEW

**Comment by oliverklee** [comment]
I'll approach this differently: I'll first clean up the code with php-cs-fixer, and then put the PhpStorm autoformat on top of that. Closing this PR for now.

**Comment by mjaschen** [comment]
(Please don't remove the vertical alignments around the assigment operators in the array definitions of the Type classes when running any automatic formatters. I added those aligments consciously for a better readability.)

**Comment by oliverklee** [comment]
Okay, will do. Thanks for letting me know!

**Comment by oliverklee** [comment]
BTW, are you aware of the discussions around vertical alignment being more readable vs. creating busywork and requiring changes to unrelated lines if something longer gets added? http://www.zeyalabs.ch/posts/2013/vertical-alignment-sucks/

**Pull request closed without merging**
