### PR TITLE
Added various Types

### PR DESCRIPTION
**Pull request by Argee88**
- ProductPrice
- ProductPriceGet
- StockAvailable
- StockAvailableGet
- Stock
- StockGet

### CODE REVIEW

**Comment by mjaschen** [comment]
Thanks!

**Comment by Argee88** [comment]
You're welcome. Will those changes be available on an composer install already?

One thing to note for the documentation would be that collmex seems to be doing some heavy processing on the StockAvailableGet. I have arround 1200 products in collmex and a request is taking between 25 and 28 seconds.

**Comment by mjaschen** [comment]
> Will those changes be available on an composer install already?

Yes, just do a `composer require mjaschen/collmex` or `composer update mjaschen/collmex`. The changes are in version 0.6.12.

**Comment by mjaschen** [comment]
Maybe you can add a comment to the `StockAvailableGet` regarding the long response times and create a pull-request?

**Comment by Argee88** [comment]
Sure, will do

**Pull request merged**
