### PR TITLE
[CLEANUP] Polish the changelog

### PR DESCRIPTION
**Pull request by oliverklee**
- add additional blank lines between versions
- use HTTPS for the semver link
- limit the lines to 80 characters

### CODE REVIEW

**Comment by oliverklee** [comment]
Ah, thanks for the pointer. I hadn't known that. Will do!

**Comment by oliverklee** [comment]
Done and repushed.

**Comment by oliverklee** [comment]
@mjaschen By the way, would you like me to always add a changelog entry as part of future PRs?

**Comment by mjaschen** [comment]
I think that's a good idea if a change is relevant for the user of this library.

It's not needed for simple formatting stuff or things like changes in the CI configuration, IMHO.

**Comment by oliverklee** [comment]
Okay, thanks. Will do!

**Pull request merged**
