### PR TITLE
[TASK] Add Travis and Packagist badges to the README

### PR DESCRIPTION
**Pull request by oliverklee**

### CODE REVIEW

**Comment by oliverklee** [comment]
Resolving the merge conflict now. Hold on …

**Comment by oliverklee** [comment]
Merged and repushed.

**Comment by oliverklee** [comment]
Rebased and repushed.

**Comment by oliverklee** [comment]
@mjaschen Do you need anything else from me so you can merge this PR?

**Comment by mjaschen** [comment]
I think, I'll skip this one as I see no benefits for adding those images, at least at the top of the document. If openend in an editor (possibly even on a small screen oder terminal emulator window) I've to scroll several lines down to reach the actual content.

**Comment by oliverklee** [comment]
@mjaschen Thanks for your reply.
The main benefit is having links to Travis and Packagist easily accessible. If you prefer, I can also just add two links instead of the buttons.

**Comment by mjaschen** [comment]
Yes, that would be clearly a win in readability.

**Comment by oliverklee** [comment]
Should I keep the Travis badge? Then the current build status would be visible in the repository start page.

**Comment by mjaschen** [comment]
I think a simple link is sufficient ;-)

**Comment by oliverklee** [comment]
Okay, done and repushed.

**Comment by mjaschen** [comment]
Thanks, great!

I'll wait for Travis and merge then.

**Pull request merged**
