### PR TITLE
fix typo in types

### PR DESCRIPTION
**Pull request by Naoray**
This fixes a typo in `TypeFactory`.

I get an error if I call `$response->getRecords()` with the current setting.

### CODE REVIEW

**Comment by mjaschen** [comment]
That's a quite interesting one, as [the documentation lists][accbal] `ACCBAL` as the type identifier.

Can you check the actual type identifier by dumping the raw response data with `CsvResponse::getResponseRaw()`?

[accbal]: https://www.collmex.de/cgi-bin/cgi.exe?1005,1,help,api_Salden

**Comment by Naoray** [comment]
Already checked... getting ACC_BAL as type Identifier

**Comment by mjaschen** [comment]
Ok, I'll ask the Collmex support what's going on here :-)

**Comment by Naoray** [comment]
But in [their dokumentation](https://www.collmex.de/cgi-bin/cgi.exe?1005,1,help,api_Salden) they actual mention that `Als Ergebnis werden Datensätze der Satzart ACC_BAL zurückgegeben.`

**Comment by mjaschen** [comment]
Yesterday was `ACCBAL` listed exactly on that page. 

I wrote to the support and suppose that they fixed the documentation in the meantime. I'm waiting for their reply an will merge your PR then.

**Comment by mjaschen** [comment]
Here we go:

> vielen Dank für den Hinweis. Die Dokumentation wurde korrigiert.

I'll merge now. 

Thanks!

**Pull request closed without merging**
