### PR TITLE
Hotfix: Default param error within customer order and invoice regarding to Collmex conversation

### PR DESCRIPTION
**Pull request by Johnny99211**
Hi Marcus,

just talked with Collmex about the fact that the default "Schlusstext" Baustein is not automatically set. Regarding to this I've changed the default param value of the regarding field. Tested and works now.

Collmex answer:

In diesem Datensatz ist das Feld für den Schlusstext leer. Entsprechend
ist auch der Schlusstext in der Rechnung leer, d.h. beim Anlegen der
Rechnung in Collmex wird zuerst der Standard-Textbaustein gesetzt, dann
aber mit der übergebenen leeren Zeichenkette überschrieben.

Damit für Zeichenfelder das Feld nicht geändert wird, muss zur Lösung
des Problems der Wert `(NULL) `übergeben werden.

If possible, please do a short hotfix so that I can run a composer update.

### CODE REVIEW

**Comment by mjaschen** [comment]
I've never noticed the possibility to provide `(NULL)` – do you know if that's a feature they've added recently?

I'll merge your PR ASAP.

**Comment by Johnny99211** [comment]
I also dont know. If you check the docs here: 

http://www.collmex.de/c.cmx?1005,1,help,daten_importieren_kundenauftraege

Search for (NULL). I thought all the time that they mean the type null and not a string `(NULL)`. It was relevant because a customer from me found out that the Standard Textbaustein is not set automatically during imports over the API. Strange thing from Collmex but ok...

**Comment by Johnny99211** [comment]
Also check:

https://www.collmex.de/c.cmx?1005,1,help,daten_importieren_datentypen_felder

**Comment by mjaschen** [comment]
Yeah, saw that and was wondering if `(NULL)` was there in the past ;-)

It seems that the default values of `null` for almost all fields in all classes have to be transformed to `(NULL)` when creating the CSV for Collmex API. I'll take a look in the next days.

**Comment by Johnny99211** [comment]
Actually, I don't think so. There are just some fields that can have (NULL) regarding the API docs. But just check it - maybe its a breaking change they've done without notice us like always..

**Pull request merged**
