### PR TITLE
added new properties: handover_required, last_handover

### PR DESCRIPTION
**Pull request by Argee88**

### CODE REVIEW

**Comment by mjaschen** [comment]
Both properties already exist in *master* (and in *0.9.0*):

https://github.com/mjaschen/collmex/blob/9cfa1854ed690644e9324d2522e69d8721d0f41b/src/Type/Delivery.php#L156-L157

**Comment by Argee88** [comment]
embarrassing... :D

**Comment by Argee88** [comment]
But it's not in the 0.9 release yet!

**Comment by mjaschen** [comment]
Hi @Argee88 

you may update to 0.9.1, that should include all changes. Can you confirm?

**Comment by Argee88** [comment]
When I try to install 0.9.1, I get the error:

Problem 1
    - The requested package mjaschen/collmex 0.9.1 exists as mjaschen/collmex[0.1.2, 0.1.3, 0.1.4, 0.2.0, 0.2.1, 0.2.2, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.6.0, 0.6.1, 0.6.10, 0.6.11, 0.6.12, 0.6.13, 0.6.14,
0.6.15, 0.6.16, 0.6.18, 0.6.19, 0.6.2, 0.6.20, 0.6.21, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.6.7, 0.6.8, 0.6.9, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.8.0, 0.8.1, 0.8.10, 0.8.11, 0.8.12, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.8, 0.8.9, 0.9.0, dev-feat_exception_chaining, dev-master] but these are rejected by your constraint.

any ideas, why that may happen?

**Comment by mjaschen** [comment]
GitHub didn’t notify Packagist, I‘ll take a look

**Comment by mjaschen** [comment]
I've updated Packagist manually, `composer update` should work now.

**Comment by mjaschen** [comment]
https://www.githubstatus.com/incidents/kq75qp7try8t

**Comment by Argee88** [comment]
jepp, can confirm... thanks for updating!
closing now

**Comment by Argee88** [comment]
yeah... but now there is the 'quantitiy' typo again...

**Comment by mjaschen** [comment]
Hi,

the fix was lost during a merge it seems. It's fixed in 0.9.2.

Sorry for the inconvenience.

**Pull request closed without merging**
